# Generated by Django 6.0.3 on 2026-04-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uniformes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('stockActual', models.IntegerField()),
                ('stockMinimo', models.IntegerField()),
                ('idPrenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='uniformes.prendas')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMovimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idDetalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uniformes.detallepedido')),
                ('idInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventario')),
            ],
        ),
    ]
