# Generated by Django 6.0.3 on 2026-04-06 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('uniformes', '0003_pedido_total_abono_pedido_total_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='idInventario',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='idPrenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='uniformes.prendas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
