# Generated by Django 6.0.3 on 2026-03-25 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0006_usuario_reset_intentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('IdLocal', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_local', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Ubicacion_direccion', models.CharField(max_length=255)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='locales/')),
                ('Horaapertura', models.TimeField()),
                ('HoraCierre', models.TimeField()),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='usuario.usuario')),
            ],
        ),
    ]
