# Generated by Django 6.0.3 on 2026-03-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='HoraCierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='Horaapertura',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
