# Generated by Django 6.0.3 on 2026-04-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_alter_local_horacierre_alter_local_horaapertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='EstaActivo',
            field=models.BooleanField(default=True),
        ),
    ]
