# Generated by Django 5.1.6 on 2026-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_local_estaactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='DesactivadoPorAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
