# Generated by Django 5.1.6 on 2026-06-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0004_local_desactivadoporadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='DesactivadoPorAdmin',
        ),
    ]
