# Generated by Django 5.1.6 on 2026-06-13 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0005_remove_local_desactivadoporadmin'),
        ('usuario', '0016_remove_usuario_es_perfil_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(default='info', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuario.usuario')),
            ],
        ),
    ]
