# Generated by Django 5.1.6 on 2026-06-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0006_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='Numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
