# Generated by Django 6.0.3 on 2026-04-04 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locales', '0002_alter_local_horacierre_alter_local_horaapertura'),
        ('usuario', '0008_alter_rol_id_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uniformes.estadopedido')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=50)),
                ('estado_pago', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente')], max_length=50)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionPedido',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('valoracion', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Prendas',
            fields=[
                ('idPrenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prendas/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('material', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('tipoPrenda', models.CharField(choices=[('Unidad', 'Prenda Completa')], max_length=50)),
                ('idLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='locales.local')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('talla', models.CharField(max_length=3)),
                ('abono', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes.pedido')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uniformes.prendas')),
            ],
        ),
    ]
