# Generated by Django 6.0.3 on 2026-04-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='tipoPrenda',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('completa', 'Prenda Completa')], max_length=50),
        ),
    ]
