# Generated by Django 6.0.3 on 2026-04-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0002_alter_prendas_tipoprenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
