# Generated by Django 6.0.3 on 2026-04-07 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0003_pedido_total_abono_pedido_total_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='estadopedido',
            name='fecha_cambio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadopedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='uniformes.pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadopedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50),
        ),
    ]
