# Generated by Django 6.0.3 on 2026-04-07 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_local_estaactivo'),
        ('uniformes', '0004_remove_pedido_estado_estadopedido_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionpedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='calificacionpedido',
            name='locales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locales.local'),
            preserve_default=False,
        ),
    ]
