# Generated by Django 6.0.3 on 2026-04-07 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0005_remove_calificacionpedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionpedido',
            name='fecha_calificacion',
        ),
    ]
