# Generated by Django 6.0.3 on 2026-04-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0006_remove_calificacionpedido_fecha_calificacion'),
        ('usuario', '0008_alter_rol_id_alter_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadopedido',
            name='fecha_cambio',
        ),
        migrations.RemoveField(
            model_name='estadopedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='idusuario',
        ),
        migrations.AddField(
            model_name='calificacionpedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calificacionpedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='uniformes.estadopedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniformes.prendas'),
        ),
    ]
