# Generated by Django 6.0.3 on 2026-04-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0007_remove_estadopedido_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionpedido',
            name='fecha',
        ),
    ]
