# Generated by Django 6.0.3 on 2026-04-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0008_remove_calificacionpedido_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='abono',
            new_name='total_abono',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_abono',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_pedido',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
