# Generated by Django 6.0.3 on 2026-04-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0009_rename_abono_detallepedido_total_abono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='total_venta',
        ),
    ]
