# Generated by Django 6.0.3 on 2026-04-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0010_remove_detallepedido_total_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='num_pedido_cliente',
            field=models.PositiveIntegerField(default=1, help_text='Secuencia de pedido para el cliente'),
        ),
    ]
