# Generated by Django 5.1.6 on 2026-05-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0011_pedido_num_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
