# Generated by Django 5.1.6 on 2026-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0014_alter_estadopedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('En Proceso', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50),
        ),
    ]
