# Generated by Django 5.1.6 on 2026-05-16 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0015_alter_estadopedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='material',
            field=models.CharField(choices=[('Algodon', 'Algodón'), ('Malla', 'Malla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prendas',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
