# Generated by Django 5.1.6 on 2026-05-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0016_alter_prendas_material_alter_prendas_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
