# Generated by Django 5.1.6 on 2026-05-17 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0017_prendas_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
