# Generated by Django 5.1.6 on 2026-06-08 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0019_populate_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionpedido',
            name='valoracion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
