# Generated by Django 5.1.6 on 2026-06-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0020_alter_calificacionpedido_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionpedido',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calificacionpedido',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
