# Generated by Django 5.1.6 on 2026-06-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0022_calificacionpedido_esta_visible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionpedido',
            name='esta_visible',
        ),
        migrations.RemoveField(
            model_name='calificacionpedido',
            name='estado_moderacion',
        ),
        migrations.RemoveField(
            model_name='calificacionpedido',
            name='motivo_deteccion',
        ),
    ]
