# Generated by Django 5.1.6 on 2026-06-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniformes', '0023_remove_calificacionpedido_esta_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionpedido',
            name='esta_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calificacionpedido',
            name='estado_moderacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('ADVERTIDO', 'Advertido'), ('BLOQUEADO', 'Bloqueado')], default='REVISADO', max_length=20),
        ),
        migrations.AddField(
            model_name='calificacionpedido',
            name='motivo_deteccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
