# Generated by Django 5.1.6 on 2026-05-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_rol_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='num_identificacion',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
