# Generated by Django 5.1.6 on 2026-05-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_num_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='num_identificacion',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
