# Generated by Django 5.1.6 on 2026-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_setup_google_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_perfil_completo',
            field=models.BooleanField(default=False),
        ),
    ]
