# Generated by Django 5.1.6 on 2026-06-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_usuario_es_perfil_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_perfil_completo',
        ),
    ]
