# Generated by Django 5.1.6 on 2026-07-03 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_usuario_bloqueado_hasta_usuario_motivo_bloqueo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 3, 12, 20, 45, 492858, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
